name: Deploy to mztradingsnapshotcdn
on:
  push:
    branches: main
  workflow_run:
    workflows: ["Publish snapshots"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # permissions:
    #   id-token: write # Needed for auth with Deno Deploy
    #   contents: read # Needed to clone the repository     ## due to issues related to github action job trigger this, the token is not available

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all commits to ensure the latest state is available
          ref: main        # Ensure the latest state from the main branch is checked out
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x  # or pin to specific like v1.46.3          
      - name: Install deployctl
        run: deno install -gArf jsr:@deno/deployctl
      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          deployctl deploy --prod \
            --project=mztradingsnapshotcdn \
            --entrypoint=api/snapshot-cdn.ts
