name: Deploy to mztrading-data
on:
  push:
    branches: main
  workflow_run:
    workflows: 
      - CBOE options rolling parquet
      - CBOE options OI Anomaly
      - CBOE options daily parquet
      - Publish snapshots v2
    branches: [main]
    types: 
      - completed
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all commits to ensure the latest state is available
          ref: main        # Ensure the latest state from the main branch is checked out
          fetch-tags: 'false'
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x  # or pin to specific like v1.46.3          
      - name: Install deployctl
        run: deno install -gArf jsr:@deno/deployctl
      - name: Deploy to Deno Deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: |
          deployctl deploy --prod \
            --project=mztrading-data \
            --entrypoint=main.ts