name: Publish ticker options data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-6'

permissions:
  contents: write

jobs:
  set-release-vars:
    runs-on: ubuntu-latest    
    outputs:
      options-data-tag: ${{ steps.tradierdata.outputs.RELEASE_NAME }}
      
    steps:
      - id: tradierdata
        run: echo "RELEASE_NAME=OPTIONS_DATA_$(date --rfc-3339=date)" >> ${GITHUB_OUTPUT}

  publish_options_data:
    runs-on: ubuntu-latest
    needs: set-release-vars
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.options-data-tag}}
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run job
        run: deno run --allow-all jobs/main-options-historical.ts
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: tradier-data
          if-no-files-found: error
          path: |
            ${{ github.workspace}}/data/options-data.summary.json
            ${{ github.workspace}}/temp/options-historical/*.json
  release-tradier-data:
    runs-on: ubuntu-latest
    needs: [set-release-vars, publish_options_data]
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.options-data-tag}}
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all commits to ensure the latest state is available
          ref: main
      - name: Download Tradier Artifact
        uses: actions/download-artifact@v4
        with:
          name: tradier-data
      # - name: Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "temp/options-historical/*.json"
      #     tag: ${{ env.RELEASE_NAME }}
      #     commit: "main"
      #     allowUpdates: "true"
      #     artifactErrorsFailBuild: "true"
      - name: Release
        uses: mnsrulz/action-gh-release@master
        with:
          files: "temp/options-historical/*.json"
          tag_name: ${{ env.RELEASE_NAME }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "publish options data (via GitHub Actions)"
            git push
          fi
