name: Publish snapshots v2

on:
  workflow_run:
    workflows: ["CBOE options rolling parquet"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch: # Allow manual trigger from GitHub Actions UI
    inputs:
      forceDayId:
        description: 'Optional day ID to force the snapshot for a specific date. Format: YYYY-MM-DD e.g. 2023-10-01'
        required: false
        type: string

permissions:
  contents: write

jobs:
  set-release-vars:    
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    outputs:
      snapshot-data-tag: ${{ steps.snapshotimages.outputs.RELEASE_NAME }}
    steps:
      - id: snapshotimages
        run: |
          if [ -n "${{ github.event.inputs.forceDayId }}" ]; then
            echo "RELEASE_NAME=DEX_GEX_SNAPSHOT_${{ github.event.inputs.forceDayId }}" >> ${GITHUB_OUTPUT}
          else
            echo "RELEASE_NAME=DEX_GEX_SNAPSHOT_$(date --rfc-3339=date)" >> ${GITHUB_OUTPUT}
          fi

  split-batches:
    runs-on: ubuntu-latest
    needs: set-release-vars
    outputs:
      batches: ${{ steps.make_batches.outputs.batches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Create batch files
        id: make_batches
        env:
          FORCE_DAY_ID: ${{ github.event.inputs.forceDayId }}
          BATCH_CHUNK_SIZE: 100
        run: |
          # run the helper that writes JSON files to temp/symbol-batches and prints a JSON array of filenames
          deno run --allow-all jobs/generate-snapshots/split-batches.ts
          json_content="$(cat "$GITHUB_WORKSPACE/temp/batch-manifest.json")"

          {
            echo "batches<<EOF"
            echo "$json_content"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Upload batch files artifact
        uses: actions/upload-artifact@v4
        with:
          name: symbol-batches
          if-no-files-found: error
          path: |
            ${{ github.workspace}}/data/options-snapshot.summary.json
            ${{ github.workspace}}/temp/batches/*.json
            ${{ github.workspace}}/temp/batch-manifest.json
            ${{ github.workspace}}/temp/all-symbols.json
  
  generate-snapshot-images:
    runs-on: ubuntu-22.04
    needs: [set-release-vars, split-batches]
    strategy:
      matrix:
        batchFile: ${{ fromJson(needs.split-batches.outputs.batches) }}
      fail-fast: false
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.snapshot-data-tag}}
      FORCE_DAY_ID: ${{ github.event.inputs.forceDayId }}
      BATCH_FILE: ${{ matrix.batchFile }}
      MATRIX_ID: ${{ strategy.job-index }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0   # Fetch all commits to ensure the latest state is available
        #   ref: main        # Ensure the latest state from the main branch is checked out
      - name: Download batch files
        uses: actions/download-artifact@v4
        with:
          name: symbol-batches
      - name: Install puppeteer deps
        run: sudo apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup puppeteer
        run: PUPPETEER_PRODUCT=chrome deno run -A https://deno.land/x/puppeteer@16.2.0/install.ts
      - name: Run
        run: deno run --allow-all jobs/generate-snapshots/generate-snapshot.ts
      # - name: Zip snapshot images
      #   run: |
      #     zip -j temp/options-snapshots.zip temp/options-snapshots/*
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-data-batch-${{ strategy.job-index }}
          if-no-files-found: error
          path: |
            ${{ github.workspace}}/data/options-snapshot.summary.json
            ${{ github.workspace}}/temp/options-snapshots/batch-${{ strategy.job-index }}/*.png
            
  consolidate-snapshot-data:
    runs-on: ubuntu-latest
    needs: [set-release-vars, generate-snapshot-images]
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.snapshot-data-tag}}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: temp
        #   name: snapshot-data ## CHANGED TO DOWNLOAD ALL ARTIFACTS
      - name: List all files before zipping
        run: |
          echo "Listing all files and subdirectories in temp/options-snapshots:"
          ls -lR temp
      - name: Zip snapshot images
        run: |
          zip -rj temp/options-snapshots.zip temp -i '*.png'
          cp temp/symbol-batches/temp/all-symbols.json temp/all-symbols.json
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-data
          if-no-files-found: error
          path: |
            ${{ github.workspace}}/temp/options-snapshots.zip
            ${{ github.workspace}}/temp/all-symbols.json
  release-snapshot-data:
    runs-on: ubuntu-latest
    needs: [set-release-vars, consolidate-snapshot-data]
    env:
      RELEASE_NAME: ${{needs.set-release-vars.outputs.snapshot-data-tag}}
      FORCE_DAY_ID: ${{ github.event.inputs.forceDayId }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all commits to ensure the latest state is available
          ref: main        # Ensure the latest state from the main branch is checked out
      - name: Download snapshot images zip artifact
        uses: actions/download-artifact@v4
        with:
          name: snapshot-data
          path: temp
      - name: List all files before zipping
        run: |
          echo "Listing all files and subdirectories in workspace:"
          ls -lR ${{ github.workspace}}/temp
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run
        run: deno run --allow-all jobs/generate-snapshots/finalize-summary.ts
      - name: Release
        uses: mnsrulz/action-gh-release@master
        with:
          files: "temp/options-snapshots.zip"
          tag_name: ${{ env.RELEASE_NAME }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "publish snapshot images data (via GitHub Actions)"
            git push
          fi
